spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/airportdb?useUnicode=true
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: es878790
    type: com.alibaba.druid.pool.DruidDataSource
